- cmd: ".gdev alltags"
  alias: "at"
  desc: "Sends tags from all guilds."
  cooldown: "Can be used 2 times every 5.0 seconds per user."

- cmd: ".gdev on"
  alias: "Nil"
  desc: "Sets `Developer Mode` on."
  cooldown: "Can be used 2 times every 5.0 seconds per user."

- cmd: ".gdev off"
  alias: "Nil"
  desc: "Sets `Developer Mode` off."
  cooldown: "Can be used 2 times every 5.0 seconds per user."

- cmd: ".gdev total-guilds"
  alias: "tg"
  desc: "Sends entire guild list."
  cooldown: "Can be used 2 times every 5.0 seconds per user."

- cmd: ".gdev no-prefix"
  alias: "np"
  desc: "Sets prefix to ' ' (empty string)"
  cooldown: "Can be used 2 times every 5.0 seconds per user."
